### ISSUE TITLE
Handling incorrect path type

### ISSUE THREAD

**Issue by lukebrobbs** [lukebrobbs/commit-hooks#2]
When running pre-commit, the following error is shown in the terminal:

![image](https://user-images.githubusercontent.com/34066386/55871886-916a0a80-5b83-11e9-997b-4ad2b677ab21.png)

Correct error handling should fix this issue

**Comment by Josephaberry54** [comment]
Need to add a type check to account for user error

**Comment by lukebrobbs** [comment]
Perhaps typescript would be worth a look? This error is caused by the user passing the incorrect type to the cypress arg in the `.commithooksrc` file

**Comment by lukebrobbs** [comment]
Added Typescript to project, also extra check for cypress and robot config args
